site_name: Dokumentasi CP Danniel
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:  
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: teal
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: teal
      accent: deep orange
  features:
    - navigation.footer

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  
  - tables

extra:
  social:
    - icon: fontawesome/brands/whatsapp
      link: https://wa.me/6282136390957
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/danniel-ang-47684b277/